services:
  database-content:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 4032
    ports:
      - "4032:5432"
    volumes:
      - contentdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=contentdatabase
  app-content:
    build: .
    restart: always
    network_mode: bridge
    container_name: content_microservice
    expose:
      - 4000
      - 4001
    ports:
      - 4000:4000
      - 4001:4001
    depends_on:
      - database-content
    links:
      - database-content
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-content:5432/contentdatabase
volumes:
  contentdata: